# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 56d284524ffbbf7a12d37c7f8c678d9ab4069a1c2e0cefec905d1c72f0d93f76e14e55dec52e95f743323a123dc5d7883a8490ccfe49a71c00eb7328b71c911b

test:
  secret_key_base: 3d729450e1ff8fc95538e776860c87e33ecd6cbd90864f4b153cb374296d6feb58df9ec5725a232b32287b107ba2ce99421aa5356776ec6082876d80b4e4e1f3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
